import type { CaseStudyTranslations } from './index';

export const zigomaCaseStudy: CaseStudyTranslations = {
  fr: {
    context: 'ZIGOMA est un ERP métier modulaire conçu pour réunir dans un même produit les opérations quotidiennes d’une PME. Le système relie la relation client, la vente, la facturation, les stocks, les projets et la finance.',
    businessProblem: 'Lorsque ces activités vivent dans des outils séparés, les données sont ressaisies, les workflows deviennent manuels et la visibilité opérationnelle se dégrade. Le produit vise une continuité entre CRM, devis, commandes, livraison, facture et suivi financier.',
    roles: ['Lead Developer', 'Développement full-stack', 'Architecture logicielle', 'IA appliquée', 'Ingénierie produit', 'Décisions UX', 'Stratégie de tests'],
    solution: 'Le produit articule des modules métier autour de flux communs : CRM, ventes, devis, commandes, bons de livraison, facturation, stock, projets, finance, analytics et assistant IA. Les actions sensibles restent soumises aux rôles, aux permissions et à une validation humaine.',
    capabilities: ['CRM et suivi commercial', 'Devis, commandes et bons de livraison', 'Facturation', 'Mouvements de stock', 'Gestion de projets', 'Finance et comptabilité', 'Tableaux de bord', 'Assistant métier contextualisé', 'Multi-entreprise et RBAC'],
    architecture: { summary: 'Une séparation par couches permet de faire évoluer les domaines métier sans confondre interface, règles, stockage et intégrations. Le schéma présente une vue conceptuelle, sans exposer de code privé.', layers: ['Interface et expérience utilisateur', 'Application et orchestration', 'Services et modules métier', 'Données et contrôles de cohérence', 'IA contextualisée et intégrations'] },
    aiLayer: { summary: 'L’IA est intégrée au contexte métier : elle peut aider à comprendre, structurer et proposer, mais ne contourne ni les permissions ni les validations. BASE et la voix font partie des modalités d’interaction.', capabilities: ['Contexte métier et capacités ciblées', 'BASE et interaction vocale', 'Raisonnement structuré', 'Contrôle des permissions', 'Validation humaine', 'Garde-fous et traçabilité'] },
    challenges: [
      { title: 'Comptabilité en partie double', detail: 'Préserver l’équilibre des écritures et la cohérence des flux financiers.' },
      { title: 'Idempotence', detail: 'Éviter qu’une action répétée produise plusieurs effets métier.' },
      { title: 'Contrôles de période', detail: 'Respecter les périodes comptables lors des opérations financières.' },
      { title: 'Transferts de stock atomiques', detail: 'Conserver un état cohérent de part et d’autre d’un transfert.' },
      { title: 'Isolation multi-entreprise', detail: 'Séparer les données et les opérations selon l’entreprise active.' },
      { title: 'RBAC', detail: 'Aligner les actions disponibles sur les rôles et permissions.' },
      { title: 'Anti-double facturation', detail: 'Protéger les flux documentaires contre les factures en doublon.' },
      { title: 'Auditabilité et tests', detail: 'Rendre les décisions et transitions métier vérifiables.' },
    ],
    outcomes: ['Un parcours métier continu de la relation client à la facture.', 'Des opérations financières et de stock conçues pour rester contrôlables.', 'Une assistance IA intégrée au produit avec validation humaine.'],
  },
  en: {
    context: 'ZIGOMA is a modular business ERP designed to bring an SME’s daily operations into one product. It connects customer relationships, sales, invoicing, stock, projects and finance.',
    businessProblem: 'When those activities live in separate tools, data is entered repeatedly, workflows become manual and operational visibility suffers. The product aims for continuity across CRM, quotes, orders, delivery, invoicing and financial follow-up.',
    roles: ['Lead Developer', 'Full-stack engineering', 'Software architecture', 'Applied AI', 'Product engineering', 'UX decisions', 'Testing strategy'],
    solution: 'The product organizes business modules around connected workflows: CRM, sales, quotes, orders, delivery notes, invoicing, stock, projects, finance, analytics and an AI assistant. Sensitive actions remain subject to roles, permissions and human validation.',
    capabilities: ['CRM and sales tracking', 'Quotes, orders and delivery notes', 'Invoicing', 'Stock movements', 'Project management', 'Finance and accounting', 'Dashboards', 'Contextual business assistant', 'Multi-company and RBAC'],
    architecture: { summary: 'Layered boundaries allow business domains to evolve without mixing interface, rules, storage and integrations. This is a conceptual view and exposes no private code.', layers: ['User interface and experience', 'Application and orchestration', 'Business services and modules', 'Data and consistency controls', 'Contextual AI and integrations'] },
    aiLayer: { summary: 'AI works within business context: it can help interpret, structure and propose, but cannot bypass permissions or validation. BASE and voice provide additional ways to interact.', capabilities: ['Business context and targeted capabilities', 'BASE and voice interaction', 'Structured reasoning', 'Permission checks', 'Human validation', 'Guardrails and traceability'] },
    challenges: [
      { title: 'Double-entry accounting', detail: 'Preserving balanced entries and consistent financial flows.' },
      { title: 'Idempotence', detail: 'Preventing repeated actions from producing duplicate business effects.' },
      { title: 'Accounting period controls', detail: 'Respecting accounting periods in financial operations.' },
      { title: 'Atomic stock transfers', detail: 'Keeping both sides of a transfer consistent.' },
      { title: 'Multi-company isolation', detail: 'Separating data and actions by the active company.' },
      { title: 'RBAC', detail: 'Aligning available actions with roles and permissions.' },
      { title: 'Anti-double billing', detail: 'Protecting document flows against duplicate invoices.' },
      { title: 'Auditability and testing', detail: 'Making business decisions and transitions verifiable.' },
    ],
    outcomes: ['A connected business flow from customer relationship to invoice.', 'Financial and stock operations designed to remain controllable.', 'AI assistance integrated into the product with human validation.'],
  },
  es: {
    context: 'ZIGOMA es un ERP empresarial modular diseñado para reunir las operaciones diarias de una pyme en un solo producto. Conecta clientes, ventas, facturación, inventario, proyectos y finanzas.',
    businessProblem: 'Cuando estas actividades están en herramientas separadas, se duplican los datos, los procesos se vuelven manuales y disminuye la visibilidad operativa. El producto busca continuidad entre CRM, presupuestos, pedidos, entregas, facturas y seguimiento financiero.',
    roles: ['Lead Developer', 'Desarrollo full-stack', 'Arquitectura de software', 'IA aplicada', 'Ingeniería de producto', 'Decisiones UX', 'Estrategia de pruebas'],
    solution: 'El producto organiza módulos empresariales en flujos conectados: CRM, ventas, presupuestos, pedidos, albaranes, facturación, inventario, proyectos, finanzas, análisis y un asistente de IA. Las acciones sensibles dependen de roles, permisos y validación humana.',
    capabilities: ['CRM y seguimiento comercial', 'Presupuestos, pedidos y albaranes', 'Facturación', 'Movimientos de inventario', 'Gestión de proyectos', 'Finanzas y contabilidad', 'Paneles de control', 'Asistente empresarial contextual', 'Multiempresa y RBAC'],
    architecture: { summary: 'La separación por capas permite evolucionar los dominios sin mezclar interfaz, reglas, almacenamiento e integraciones. Es una vista conceptual que no expone código privado.', layers: ['Interfaz y experiencia de usuario', 'Aplicación y orquestación', 'Servicios y módulos empresariales', 'Datos y controles de coherencia', 'IA contextual e integraciones'] },
    aiLayer: { summary: 'La IA opera dentro del contexto empresarial: ayuda a interpretar, estructurar y proponer, pero no evita permisos ni validaciones. BASE y voz ofrecen otras formas de interacción.', capabilities: ['Contexto empresarial y capacidades específicas', 'BASE e interacción por voz', 'Razonamiento estructurado', 'Control de permisos', 'Validación humana', 'Salvaguardas y trazabilidad'] },
    challenges: [
      { title: 'Contabilidad de partida doble', detail: 'Mantener el equilibrio de asientos y flujos financieros.' },
      { title: 'Idempotencia', detail: 'Evitar efectos duplicados al repetir una acción.' },
      { title: 'Control de períodos contables', detail: 'Respetar los períodos en las operaciones financieras.' },
      { title: 'Transferencias atómicas de inventario', detail: 'Mantener coherencia en ambos lados de la transferencia.' },
      { title: 'Aislamiento multiempresa', detail: 'Separar datos y operaciones por empresa activa.' },
      { title: 'RBAC', detail: 'Alinear acciones disponibles con roles y permisos.' },
      { title: 'Prevención de facturas duplicadas', detail: 'Proteger los flujos documentales contra duplicados.' },
      { title: 'Auditabilidad y pruebas', detail: 'Hacer verificables las decisiones y transiciones empresariales.' },
    ],
    outcomes: ['Un flujo continuo desde la relación con el cliente hasta la factura.', 'Operaciones financieras y de inventario diseñadas para mantenerse controlables.', 'Asistencia de IA integrada en el producto con validación humana.'],
  },
};
