import type { LanguageCode } from '../constants/i18n';

export const privacyContact = 'teranhenryc@gmail.com';
type Policy = { title: string; description: string; sections: { title: string; text: string }[] };
export const policies: Record<LanguageCode, Policy> = {
  fr: {
    title: 'Politique de confidentialité', description: 'Vos données, les formulaires de contact et vos choix concernant les cookies et Google Analytics.',
    sections: [
      { title: 'Responsable du traitement', text: 'Henry Teran, Genève, Suisse. Pour toute question ou demande relative à vos données, contactez l’adresse ci-dessous.' },
      { title: 'Données des formulaires', text: 'Contact transmet votre nom, email, message et langue. Project Brief transmet votre nom, email, téléphone et entreprise éventuels, type et description du projet, fonctionnalités, technologies, planning, budget, urgence, besoins complémentaires (design, hébergement, maintenance, formation), informations libres et langue. Évitez de transmettre des données sensibles ou celles de tiers sans nécessité.' },
      { title: 'Utilisation des données', text: 'Ces informations servent à répondre à votre demande, évaluer une collaboration, comprendre un besoin projet, préparer une réponse professionnelle ou commerciale et assurer le suivi. Ce traitement répond à votre démarche de contact ou à votre demande précontractuelle ; les données ne sont pas utilisées pour une newsletter ou de la publicité.' },
      { title: 'Destinataires et services techniques', text: 'Henry Teran reçoit les demandes par email. Vercel assure l’hébergement et les fonctions serveur ; Gmail (Google) assure l’envoi et la réception des emails dans la configuration actuelle. Les services techniques peuvent traiter des métadonnées de connexion (adresse IP, date, informations techniques) nécessaires à la fourniture et à la sécurité du service. Google Analytics 4 reçoit des informations de navigation uniquement si vous activez Analytics. Le contenu des formulaires n’est pas transmis à GA4 par ce site.' },
      { title: 'Conservation', text: 'Les données sont conservées uniquement pendant la durée nécessaire au traitement et au suivi de la demande et aux obligations légales éventuelles. Aucune durée uniforme supplémentaire n’est imposée ici aux échanges professionnels.' },
      { title: 'Confirmation email et protection anti-spam', text: 'Une demande doit être confirmée par email avant sa transmission à Henry. Le lien expire après 20 minutes. Les données non confirmées sont supprimées du stockage temporaire au plus tard à cette échéance ; après confirmation, elles sont retirées de ce stockage et transmises par email. La protection utilise Cloudflare Turnstile et, lorsqu’il est configuré, un stockage Redis REST Upstash. Des empreintes protégées de l’adresse IP, de l’email et de la demande limitent les abus et doublons pendant 15 à 60 minutes. Le hash du token aléatoire et un état technique peuvent être conservés jusqu’à 24 heures, sans le contenu du formulaire. Ces traitements assurent la sécurité, sans finalité publicitaire. Cloudflare et Upstash peuvent traiter les données techniques et temporaires hors de Suisse/EEE selon leur configuration. Les emails confirmés suivent la politique de conservation des échanges décrite ci-dessus.' },
      { title: 'Vos droits', text: 'Vous pouvez demander l’accès et la rectification de vos données, leur suppression ou vous opposer au traitement lorsque ces droits s’appliquent. Écrivez à l’adresse ci-dessous en précisant votre demande. Vous pouvez retirer votre consentement Analytics à tout moment via les préférences cookies ; ce retrait concerne les traitements futurs.' },
      { title: 'Services internationaux', text: 'Vercel et Google sont des fournisseurs internationaux. Des données peuvent être traitées hors de Suisse et de l’EEE, notamment aux États-Unis, selon les services et leur configuration. Leurs politiques de confidentialité décrivent leurs lieux de traitement et mécanismes de transfert ; cette page ne constitue pas une garantie de localisation exclusive en Suisse.' },
      { title: 'Sécurité', text: 'Le site valide les données côté serveur, conserve les identifiants SMTP côté serveur et limite le contenu des erreurs retournées. Ces mesures réduisent les risques sans garantir une sécurité absolue.' },
      { title: 'Stockage nécessaire et préférences', text: 'Le navigateur mémorise vos choix de confidentialité, de langue et de thème pour fournir l’expérience demandée. Ce stockage local ne sert pas à mesurer votre audience. Le choix de confidentialité reste sur votre appareil jusqu’à sa modification ou à l’effacement des données du navigateur. Les formulaires fonctionnent même si Analytics est refusé.' },
      { title: 'Cookies Analytics — facultatifs', text: 'GA4 est désactivé par défaut. Après votre accord, Google peut déposer des cookies _ga et _ga_* et mesurer les pages consultées, interactions et caractéristiques techniques du navigateur. Les cookies GA4 ont généralement une durée pouvant aller jusqu’à deux ans selon la configuration Google. Refuser ou retirer votre accord bloque les prochains envois ; les cookies GA4 accessibles sur ce domaine sont supprimés lors du refus. Les préférences cookies du pied de page permettent de revoir votre choix.' },
    ],
  },
  en: {
    title: 'Privacy policy', description: 'Your data, contact forms and choices about cookies and Google Analytics.',
    sections: [
      { title: 'Data controller', text: 'Henry Teran, Geneva, Switzerland. For questions or requests about your data, use the contact address below.' },
      { title: 'Form data', text: 'Contact sends your name, email, message and language. Project Brief sends your name, email, optional phone and company, project type and description, features, technologies, schedule, budget, urgency, additional needs (design, hosting, maintenance, training), free-text information and language. Avoid sending sensitive information or unnecessary third-party data.' },
      { title: 'How data is used', text: 'This information is used to answer your request, assess a collaboration, understand project requirements, prepare a professional or commercial reply and follow up. Processing responds to your contact or pre-contractual request; data is not used for newsletters or advertising.' },
      { title: 'Recipients and technical services', text: 'Henry Teran receives requests by email. Vercel provides hosting and server functions; Gmail (Google) sends and receives email in the current configuration. Technical providers may process connection metadata (IP address, date, technical information) needed to deliver and secure their services. Google Analytics 4 receives navigation information only if you enable Analytics. This site does not send form contents to GA4.' },
      { title: 'Retention', text: 'Data is kept only as long as necessary to handle and follow up on your request and meet any applicable legal obligations. No additional uniform retention period is imposed here on professional correspondence.' },
      { title: 'Email confirmation and spam protection', text: 'Requests must be confirmed by email before being forwarded to Henry. Links expire after 20 minutes. Unconfirmed form data is deleted from temporary storage by that deadline; on confirmation it is removed from that storage and sent by email. Protection uses Cloudflare Turnstile and, when configured, Upstash Redis REST storage. Protected fingerprints of the IP address, email and request limit abuse and duplicates for 15 to 60 minutes. A hash of the random token and technical status may remain for up to 24 hours without form contents. This processing is for security, not advertising. Cloudflare and Upstash may process technical and temporary data outside Switzerland/the EEA depending on configuration. Confirmed emails follow the correspondence retention policy above.' },
      { title: 'Your rights', text: 'You may request access and correction, deletion or object to processing where these rights apply. Write to the address below with your request. You can withdraw Analytics consent at any time through cookie preferences; withdrawal applies to future processing.' },
      { title: 'International services', text: 'Vercel and Google are international providers. Data may be processed outside Switzerland and the EEA, including in the United States, depending on the services and configuration. Their privacy policies describe processing locations and transfer mechanisms; this page does not guarantee exclusive storage in Switzerland.' },
      { title: 'Security', text: 'The site validates data on the server, keeps SMTP credentials on the server and limits information returned in errors. These measures reduce risks without guaranteeing absolute security.' },
      { title: 'Necessary storage and preferences', text: 'Your browser remembers privacy, language and theme choices to provide the requested experience. This local storage is not used for audience measurement. The privacy choice stays on your device until changed or browser data is cleared. Forms work even when Analytics is declined.' },
      { title: 'Analytics cookies — optional', text: 'GA4 is off by default. After you agree, Google may set _ga and _ga_* cookies and measure pages, interactions and browser characteristics. GA4 cookies typically last up to two years depending on Google configuration. Rejecting or withdrawing consent blocks subsequent sends; accessible GA4 cookies on this domain are deleted on rejection. Footer cookie preferences let you revisit your choice.' },
    ],
  },
  es: {
    title: 'Política de privacidad', description: 'Tus datos, formularios de contacto y opciones sobre cookies y Google Analytics.',
    sections: [
      { title: 'Responsable del tratamiento', text: 'Henry Teran, Ginebra, Suiza. Para preguntas o solicitudes sobre tus datos, utiliza la dirección de contacto indicada abajo.' },
      { title: 'Datos de los formularios', text: 'Contacto envía nombre, email, mensaje e idioma. Project Brief envía nombre, email, teléfono y empresa opcionales, tipo y descripción del proyecto, funcionalidades, tecnologías, calendario, presupuesto, urgencia, necesidades adicionales (diseño, alojamiento, mantenimiento, formación), información libre e idioma. Evita enviar datos sensibles o datos innecesarios de terceros.' },
      { title: 'Uso de los datos', text: 'La información permite responder a tu solicitud, evaluar una colaboración, comprender un proyecto, preparar una respuesta profesional o comercial y realizar su seguimiento. El tratamiento responde a tu contacto o solicitud precontractual; los datos no se utilizan para newsletters ni publicidad.' },
      { title: 'Destinatarios y servicios técnicos', text: 'Henry Teran recibe las solicitudes por email. Vercel proporciona alojamiento y funciones de servidor; Gmail (Google) envía y recibe los emails en la configuración actual. Los proveedores técnicos pueden tratar metadatos de conexión (dirección IP, fecha, información técnica) necesarios para prestar y proteger el servicio. Google Analytics 4 recibe información de navegación solo si activas Analytics. Este sitio no envía el contenido de los formularios a GA4.' },
      { title: 'Conservación', text: 'Los datos se conservan únicamente durante el tiempo necesario para atender y seguir la solicitud y cumplir eventuales obligaciones legales. No se establece aquí un plazo uniforme adicional para la correspondencia profesional.' },
      { title: 'Confirmación por email y protección antispam', text: 'Las solicitudes deben confirmarse por email antes de transmitirse a Henry. Los enlaces caducan en 20 minutos. Los datos sin confirmar se eliminan del almacenamiento temporal como máximo al vencer ese plazo; al confirmar, se retiran de ese almacenamiento y se envían por email. La protección utiliza Cloudflare Turnstile y, cuando se configura, almacenamiento Redis REST de Upstash. Huellas protegidas de la IP, el email y la solicitud limitan abusos y duplicados durante 15 a 60 minutos. Un hash del token aleatorio y un estado técnico pueden mantenerse hasta 24 horas sin el contenido del formulario. Este tratamiento protege el servicio, sin finalidad publicitaria. Cloudflare y Upstash pueden tratar datos técnicos y temporales fuera de Suiza/EEE según la configuración. Los emails confirmados siguen la política de conservación de correspondencia anterior.' },
      { title: 'Tus derechos', text: 'Puedes solicitar acceso, rectificación, supresión u oponerte al tratamiento cuando estos derechos sean aplicables. Escribe a la dirección indicada abajo detallando tu solicitud. Puedes retirar el consentimiento de Analytics en cualquier momento desde las preferencias de cookies; la retirada afecta a tratamientos futuros.' },
      { title: 'Servicios internacionales', text: 'Vercel y Google son proveedores internacionales. Los datos pueden tratarse fuera de Suiza y del EEE, incluidos Estados Unidos, según los servicios y su configuración. Sus políticas describen ubicaciones y mecanismos de transferencia; esta página no garantiza un almacenamiento exclusivo en Suiza.' },
      { title: 'Seguridad', text: 'El sitio valida los datos en el servidor, conserva allí las credenciales SMTP y limita la información devuelta en errores. Estas medidas reducen riesgos sin garantizar una seguridad absoluta.' },
      { title: 'Almacenamiento necesario y preferencias', text: 'El navegador recuerda tus elecciones de privacidad, idioma y tema para ofrecer la experiencia solicitada. Este almacenamiento local no mide la audiencia. La elección de privacidad permanece en tu dispositivo hasta que la cambies o borres los datos del navegador. Los formularios funcionan aunque rechaces Analytics.' },
      { title: 'Cookies Analytics — opcionales', text: 'GA4 está desactivado por defecto. Tras tu aceptación, Google puede guardar cookies _ga y _ga_* y medir páginas, interacciones y características del navegador. Las cookies GA4 suelen durar hasta dos años según la configuración de Google. Rechazar o retirar el consentimiento bloquea los siguientes envíos; las cookies GA4 accesibles en este dominio se borran al rechazar. Puedes revisar tu elección en las preferencias del pie de página.' },
    ],
  },
};
