import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import i18n from '../i18n';
import QuoteModal from '../components/QuoteModal';
import { formCopy } from './copy';
import { apiErrorMessage } from './apiErrors';
const mocks = vi.hoisted(() => ({ send: vi.fn() }));
vi.mock('../services/emailService', async original => ({ ...await original<typeof import('../services/emailService')>(), sendQuoteEmail: mocks.send }));
vi.mock('../security/Turnstile', () => ({ default: ({ onToken }: { onToken: (value: string) => void }) => <><button type="button" onClick={() => onToken('token')}>Verify test</button><button type="button" onClick={() => onToken('')}>Expire test</button></> }));
beforeEach(() => { mocks.send.mockReset(); HTMLElement.prototype.scrollTo = vi.fn(); });
const fill = (id: string, value: string) => fireEvent.change(document.getElementById('brief-' + id)!, { target: { value } });
const choose = (id: string) => fill(id, (document.getElementById('brief-' + id) as HTMLSelectElement).options[1].value);
describe('Project Brief validation UX', () => {
  it.each(['fr', 'en', 'es'])('validates each step and final security in %s', async language => {
    await i18n.changeLanguage(language);
    render(<MemoryRouter><QuoteModal isOpen onClose={() => {}} /></MemoryRouter>);
    const next = () => screen.getByRole('button', { name: i18n.t('quoteModal.buttons.next') });
    expect(next()).toBeDisabled();
    fill('name', 'Ada'); fill('email', 'invalid'); expect(next()).toBeDisabled();
    fill('email', 'ada@example.com'); expect(next()).toBeEnabled();
    fill('phone', 'abc'); fireEvent.blur(document.getElementById('brief-phone')!);
    expect(next()).toBeDisabled(); expect(document.getElementById('brief-phone')).toHaveAttribute('aria-invalid', 'true');
    fill('phone', ''); fill('company', 'x'.repeat(151)); expect(next()).toBeDisabled();
    fill('company', ''); fireEvent.click(next());
    choose('project-type'); fill('description', 'x'.repeat(49));
    expect(screen.getByText(`49 / 50 ${formCopy(language).minimum} · 4000 ${formCopy(language).maximum}`)).toBeInTheDocument();
    expect(next()).toBeDisabled();
    fill('description', 'x'.repeat(4001)); expect(next()).toBeDisabled();
    fill('description', 'x'.repeat(50)); expect(next()).toBeEnabled(); fireEvent.click(next());
    choose('timeline'); expect(next()).toBeDisabled(); choose('budget'); fireEvent.click(next());
    const submit = screen.getByRole('button', { name: i18n.t('quoteModal.buttons.submit') });
    expect(submit).toBeDisabled();
    expect(document.getElementById('brief-readiness')).toHaveTextContent(formCopy(language).security);
    fireEvent.click(screen.getByText('Verify test')); expect(submit).toBeEnabled();
    expect(screen.getByText(`✓ ${formCopy(language).briefReady}`)).toBeInTheDocument();
    fill('additional-info', 'x'.repeat(5001)); expect(submit).toBeDisabled(); fill('additional-info', '');
    fireEvent.click(screen.getByText('Expire test')); expect(submit).toBeDisabled();
    fireEvent.click(screen.getByText('Verify test'));
    mocks.send.mockImplementation(async (_data, _protection, onError) => { onError('smtp_error'); return false; });
    fireEvent.click(submit);
    expect(await screen.findByText(apiErrorMessage('smtp_error', language))).toBeInTheDocument();
    let resolve!: (value: boolean) => void;
    mocks.send.mockImplementation(() => new Promise<boolean>(done => { resolve = done; }));
    fireEvent.click(submit); expect(submit).toBeDisabled();
    resolve(true);
    await waitFor(() => expect(screen.getByRole('status')).toHaveTextContent(formCopy(language).briefSuccess));
    expect(submit).toBeDisabled();
    expect(mocks.send.mock.calls[0][0]).toMatchObject({ name: 'Ada', features: [], technologies: [] });
  });
});
