import { fireEvent, render, screen } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import i18n from '../i18n';
import Contact from '../components/Contact';
import { formCopy } from './copy';
import { apiErrorMessage } from './apiErrors';
const mocks = vi.hoisted(() => ({ send: vi.fn() }));
vi.mock('../services/emailService', async original => ({ ...await original<typeof import('../services/emailService')>(), sendContactEmail: mocks.send }));
vi.mock('../security/Turnstile', () => ({ default: ({ onToken }: { onToken: (value: string) => void }) => <><button type="button" onClick={() => onToken('token')}>Verify test</button><button type="button" onClick={() => onToken('')}>Expire test</button></> }));
beforeEach(() => { mocks.send.mockReset(); });
const fill = (id: string, value: string) => fireEvent.change(document.getElementById(id)!, { target: { value } });
describe('Contact validation UX', () => {
  it.each(['fr', 'en', 'es'])('explains validation, counters, security and errors in %s', async language => {
    await i18n.changeLanguage(language);
    render(<MemoryRouter><Contact /></MemoryRouter>);
    const button = document.querySelector<HTMLButtonElement>('#contact-form button[type="submit"]')!;
    expect(button).toBeDisabled();
    fill('name', 'A'); fireEvent.blur(document.getElementById('name')!);
    expect(document.getElementById('name')).toHaveAttribute('aria-invalid', 'true');
    fireEvent.submit(document.getElementById('contact-form')!);
    expect(document.getElementById('name')).toHaveFocus();
    fill('name', 'Ada'); fill('email', 'invalid'); fill('message', 'x'.repeat(29));
    expect(screen.getByText(`29 / 30 ${formCopy(language).minimum} · 2000 ${formCopy(language).maximum}`)).toBeInTheDocument();
    expect(button).toBeDisabled();
    fill('email', 'ada@example.com'); fill('message', 'x'.repeat(30));
    expect(button).toBeDisabled();
    fireEvent.click(screen.getByText('Verify test'));
    expect(button).toBeEnabled(); expect(screen.getByText(`✓ ${formCopy(language).contactReady}`)).toBeInTheDocument();
    fill('message', 'x'.repeat(2001)); expect(button).toBeDisabled();
    fill('message', 'x'.repeat(30)); fireEvent.click(screen.getByText('Expire test')); expect(button).toBeDisabled();
    fireEvent.click(screen.getByText('Verify test'));
    mocks.send.mockImplementation(async (_data, _protection, onError) => { onError('rate_limited'); return false; });
    fireEvent.click(button);
    expect(await screen.findByText(apiErrorMessage('rate_limited', language))).toBeInTheDocument();
    mocks.send.mockResolvedValue(true); fireEvent.click(button);
    expect(await screen.findByText(formCopy(language).contactSuccess)).toBeInTheDocument();
  });
});
